### ISSUE TITLE
Auction time discrepancies

### ISSUE THREAD

**Issue by andrewhayter** [holaplex/holaplex#143] opened 2021-12-21 09:29 UTC
An individual auction page has a shorter auction time than what is stated on the home page.

example: https://celestialbody.holaplex.com/listings/7JAZCtspZQ52x6vmadAsfEjvenreUZ19BghgVR3aDdgy vs homepage listing.

**Comment by sjc5** [comment] 2021-12-21 23:27
Thanks so much for opening the issue, @andrewhayter!

Will do some root cause analysis and report back.

Meanwhile, if you have any leads or ideas about what is happening, please feel free to post here (or even contribute a fix 😃)

**Comment by ray-kast** [comment] 2021-12-22 22:05
As of PR #144 on the frontend and [this backend PR](https://github.com/holaplex/metaplex-indexer/pull/17/files) we now be properly format the timestamps for UTC, and the countdowns on https://holaplex.com/ should now be correct.

@andrewhayter can you confirm whether this resolved your issue?

**Comment by andrewhayter** [comment] 2021-12-28 23:06
This seems to off again. Seeing a discrepancy between homepage and auction page.

**Comment by sjc5** [comment] 2021-12-28 23:13
> This seems to off again. Seeing a discrepancy between homepage and auction page.

Hmm, both holaplex.com and the storefronts are rendering the correct countdowns for me right now. 

Can you clear your browser cache or try in incognito mode and let us know if it's still off on your end?  If so, a screenshot of the differing times, your local timezone and a link to the auction would be helpful.

cc @ray-kast @kristianeboe

**Comment by ray-kast** [comment] 2021-12-28 23:19
@sjc5 @andrewhayter this may be related to the indexer backend not handling auction gap times.  this is something i have an open ticket for, I'll get on it ASAP

**Comment by andrewhayter** [comment] 2021-12-29 00:50
> @sjc5 @andrewhayter this may be related to the indexer backend not handling auction gap times. this is something i have an open ticket for, I'll get on it ASAP

I think you both might be right. Regular auctions time seems to be fixed but if an auction gets extended I believe there is something happening there. I currently have an auction that got extended that unfortunately fell off the front page.

**Comment by ray-kast** [comment] 2021-12-29 00:52
@andrewhayter I'm currently deploying a hotfix that should hopefully handle that, as per [this PR](https://github.com/holaplex/metaplex-indexer/pull/23).

**Comment by andrewhayter** [comment] 2021-12-29 01:01
Looks good! Thanks for the quick work! @ray-kast and team!

**Comment by ray-kast** [comment] 2021-12-29 01:29
The hotfix is live, it should be rolling out soon if it hasn't already.  @andrewhayter let me know if this fixes your problem.

**Comment by ray-kast** [comment] 2021-12-30 00:05
@andrewhayter closing for now (again lol).  Lemme know if you see any further problems.

**Closed by ray-kast** 2021-12-30 00:05 UTC
